### ISSUE TITLE
[enhancement] Tag and Version this project

### ISSUE THREAD

**Issue by gruyaume** [grafana/dashboard-linter#201]
# Description

We use the Grafana dashboard linter in many of our CI's to ensure we keep a consistent quality level in our dashboards.

The project is not tagged at the moment, leading us to point to the `@latest` version of the go package. 

## Impact

This resulted in all of our CI's that use the grafana dashboard linter to fail this week because of a breaking change in the linter (addition of logql rules). While this change is welcomed, it should have been associated with a new version of the project, and we could have made this change on its own. 

### GitHub action workflow

```yaml
name: Lint Grafana Dashboard

on:
  workflow_call:


jobs:
  lint-grafana:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install Grafana Dashboard Linter
        run: go install github.com/grafana/dashboard-linter@latest
      - name: Run Grafana Dashboard Lint
        run: dashboard-linter lint src/grafana_dashboards/* --strict -c grafana.lint
```
